# Generated by Django 5.0.1 on 2024-06-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_price'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='games.game'),
        ),
    ]
