# Generated by Django 5.0.1 on 2024-05-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameModes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameMultiplayerMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropin', models.BooleanField()),
                ('lancoop', models.BooleanField()),
                ('campaigncoop', models.BooleanField()),
                ('onlinecoop', models.BooleanField()),
                ('offlinecoop', models.BooleanField()),
                ('splitscreen', models.BooleanField()),
                ('offlinemax', models.IntegerField()),
                ('onlinemax', models.IntegerField()),
                ('offlinecoopmax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('animated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=50)),
                ('alternative_name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('rating_count', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('storyline', models.TextField()),
                ('status', models.CharField(choices=[('released', 'Released'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('early_access', 'Early Access'), ('offline', 'Offline'), ('cancelled', 'Cancelled'), ('rumored', 'Rumored'), ('delisted', 'Delisted')], default='released', max_length=20)),
                ('category', models.CharField(choices=[('main_game', 'Main Game'), ('dlc_addon', 'DLC Addon'), ('expansion', 'Expansion'), ('bundle', 'Bundle'), ('standalone_expansion', 'Standalone Expansion'), ('mod', 'Mod'), ('episode', 'Episode'), ('season', 'Season'), ('remake', 'Remake'), ('remaster', 'Remaster'), ('expanded_game', 'Expanded Game'), ('port', 'Port'), ('fork', 'Fork'), ('pack', 'Pack'), ('update', 'Update')], default='main_game', max_length=20)),
                ('involved_companies', models.ManyToManyField(to='games.company')),
                ('main_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_collection', to='games.collection')),
                ('other_collections', models.ManyToManyField(related_name='other_collections', to='games.collection')),
                ('game_engines', models.ManyToManyField(to='games.gameengine')),
                ('main_game_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_game_franchise', to='games.gamefranchise')),
                ('other_game_franchises', models.ManyToManyField(related_name='other_game_franchises', to='games.gamefranchise')),
                ('genres', models.ManyToManyField(to='games.gamegenre')),
                ('keywords', models.ManyToManyField(to='games.gamekeyword')),
                ('game_modes', models.ManyToManyField(to='games.gamemodes')),
                ('multiplayer_modes', models.ManyToManyField(to='games.gamemultiplayermode')),
                ('themes', models.ManyToManyField(to='games.gametheme')),
                ('game_video', models.ManyToManyField(to='games.gamevideo')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='games.image')),
                ('screenshots', models.ManyToManyField(related_name='screenshots', to='games.image')),
                ('platforms', models.ManyToManyField(to='games.platform')),
                ('player_perspectives', models.ManyToManyField(to='games.playerperspective')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='games',
            field=models.ManyToManyField(to='games.game'),
        ),
    ]
