# Generated by Django 5.0.1 on 2024-05-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='games.image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_engines',
            field=models.ManyToManyField(blank=True, null=True, to='games.gameengine'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(blank=True, null=True, to='games.gamemodes'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_video',
            field=models.ManyToManyField(blank=True, null=True, to='games.gamevideo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='games.gamegenre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='involved_companies',
            field=models.ManyToManyField(blank=True, null=True, to='games.company'),
        ),
        migrations.AlterField(
            model_name='game',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='games.gamekeyword'),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_collection', to='games.collection'),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_game_franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_game_franchise', to='games.gamefranchise'),
        ),
        migrations.AlterField(
            model_name='game',
            name='multiplayer_modes',
            field=models.ManyToManyField(blank=True, null=True, to='games.gamemultiplayermode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_collections', to='games.collection'),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_game_franchises',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_game_franchises', to='games.gamefranchise'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, null=True, to='games.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_perspectives',
            field=models.ManyToManyField(blank=True, null=True, to='games.playerperspective'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(blank=True, null=True, related_name='screenshots', to='games.image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='games.gametheme'),
        ),
    ]
