# Generated by Django 5.0.1 on 2024-05-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_cover_alter_game_game_engines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_engines',
            field=models.ManyToManyField(blank=True, to='games.gameengine'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_modes',
            field=models.ManyToManyField(blank=True, to='games.gamemodes'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_video',
            field=models.ManyToManyField(blank=True, to='games.gamevideo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, to='games.gamegenre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='involved_companies',
            field=models.ManyToManyField(blank=True, to='games.company'),
        ),
        migrations.AlterField(
            model_name='game',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='games.gamekeyword'),
        ),
        migrations.AlterField(
            model_name='game',
            name='multiplayer_modes',
            field=models.ManyToManyField(blank=True, to='games.gamemultiplayermode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_collections',
            field=models.ManyToManyField(blank=True, related_name='other_collections', to='games.collection'),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_game_franchises',
            field=models.ManyToManyField(blank=True, related_name='other_game_franchises', to='games.gamefranchise'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='games.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_perspectives',
            field=models.ManyToManyField(blank=True, to='games.playerperspective'),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='screenshots', to='games.image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, to='games.gametheme'),
        ),
    ]
