# Generated by Django 5.0.1 on 2024-05-20 22:18

import django_unixdatetimefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
    ]
