# Generated by Django 5.0.1 on 2024-05-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_collection_name_alter_collection_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevideo',
            name='video_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='animated',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
