# Generated by Django 5.0.1 on 2024-05-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_gamevideo_video_id_alter_image_animated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='animated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
