# Generated by Django 5.0.1 on 2024-05-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_game_main_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='games',
        ),
    ]
