# Generated by Django 5.0.1 on 2024-05-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_alter_gamevideo_video_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameModes',
            new_name='GameMode',
        ),
    ]
