# Generated by Django 5.0.1 on 2024-05-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_rename_gamemodes_gamemode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_video',
            new_name='game_videos',
        ),
    ]
