# Generated by Django 5.0.1 on 2024-05-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_rename_game_video_game_game_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvolvedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='games.company')),
            ],
        ),
    ]
