# Generated by Django 5.0.1 on 2024-05-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_involvedcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='multiplayer_modes',
        ),
        migrations.DeleteModel(
            name='GameMultiplayerMode',
        ),
    ]
