# Generated by Django 5.0.1 on 2024-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_remove_game_multiplayer_modes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Official'), ('2', 'Wikia'), ('3', 'Wikipedia'), ('4', 'Facebook'), ('5', 'Twitter'), ('6', 'Twitch'), ('8', 'Instagram'), ('9', 'Youtube'), ('10', 'IPhone'), ('11', 'IPad'), ('12', 'Android'), ('13', 'Steam'), ('14', 'Reddit'), ('15', 'Itch'), ('16', 'Epic Games'), ('17', 'GOG'), ('18', 'Discord')], default='1', max_length=30)),
                ('trusted', models.BooleanField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='websites',
            field=models.ManyToManyField(blank=True, related_name='websites', to='games.website'),
        ),
    ]
