# Generated by Django 5.0.1 on 2024-05-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_website_game_websites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='involved_companies',
            new_name='companies',
        ),
    ]
