# Generated by Django 5.0.1 on 2024-05-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_alter_collection_slug_alter_company_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='games.image'),
        ),
    ]
