# Generated by Django 5.0.1 on 2024-05-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_game_artworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='artworks',
        ),
        migrations.AddField(
            model_name='game',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='games.image'),
        ),
    ]
