# Generated by Django 5.0.1 on 2024-05-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_remove_game_screenshots_game_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', to='games.steamimage'),
        ),
    ]
