# Generated by Django 5.0.1 on 2024-06-10 19:40

import django.db.models.deletion
import django_unixdatetimefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('video_id', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, max_length=100)),
                ('height', models.IntegerField(blank=True)),
                ('width', models.IntegerField(blank=True)),
                ('animated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('alternative_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Official'), ('2', 'Wikia'), ('3', 'Wikipedia'), ('4', 'Facebook'), ('5', 'Twitter'), ('6', 'Twitch'), ('8', 'Instagram'), ('9', 'Youtube'), ('10', 'IPhone'), ('11', 'IPad'), ('12', 'Android'), ('13', 'Steam'), ('14', 'Reddit'), ('15', 'Itch'), ('16', 'Epic Games'), ('17', 'GOG'), ('18', 'Discord')], default='1', max_length=30)),
                ('trusted', models.BooleanField(default=True)),
                ('url', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='games.company')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('release_date', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('storyline', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Released'), ('2', 'Alpha'), ('3', 'Beta'), ('4', 'Early Access'), ('5', 'Offline'), ('6', 'Cancelled'), ('7', 'Rumored'), ('8', 'Delisted')], default='0', max_length=20)),
                ('category', models.CharField(choices=[('0', 'Main Game'), ('1', 'DLC Addon'), ('2', 'Expansion'), ('3', 'Bundle'), ('4', 'Standalone Expansion'), ('5', 'Mod'), ('6', 'Episode'), ('7', 'Season'), ('8', 'Remake'), ('9', 'Remaster'), ('10', 'Expanded Game'), ('11', 'Port'), ('12', 'Fork'), ('13', 'Pack'), ('14', 'Update')], default='0', max_length=20)),
                ('collections', models.ManyToManyField(blank=True, to='games.collection')),
                ('companies', models.ManyToManyField(blank=True, to='games.company')),
                ('game_engines', models.ManyToManyField(blank=True, to='games.gameengine')),
                ('franchises', models.ManyToManyField(blank=True, to='games.gamefranchise')),
                ('genres', models.ManyToManyField(blank=True, to='games.gamegenre')),
                ('keywords', models.ManyToManyField(blank=True, to='games.gamekeyword')),
                ('game_modes', models.ManyToManyField(blank=True, to='games.gamemode')),
                ('themes', models.ManyToManyField(blank=True, to='games.gametheme')),
                ('game_videos', models.ManyToManyField(blank=True, to='games.gamevideo')),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='games.image')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='games.image')),
                ('screenshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshot', to='games.image')),
                ('platforms', models.ManyToManyField(blank=True, to='games.platform')),
                ('player_perspectives', models.ManyToManyField(blank=True, to='games.playerperspective')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header', to='games.steamimage')),
                ('websites', models.ManyToManyField(blank=True, to='games.website')),
            ],
        ),
    ]
