# Generated by Django 5.0.1 on 2024-05-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_steamimage_game_header'),
        ('price', '0002_gameprice_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprice',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='games.game'),
        ),
    ]
