# Generated by Django 5.0.1 on 2024-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_gameprice_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
