# Generated by Django 5.0.1 on 2024-06-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_gameprice_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePrice',
        ),
    ]
