# Generated by Django 5.0.1 on 2024-06-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_gameprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprice',
            name='name',
        ),
    ]
