# Generated by Django 5.0.1 on 2024-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_gameprice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprice',
            name='latest',
            field=models.BooleanField(default=True),
        ),
    ]
