# Generated by Django 5.0.1 on 2024-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0011_gameprice_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
